AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  GraphQL:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/graphql.handler
      Runtime: nodejs14.x
      Timeout: 10
      MemorySize: 1024
      Events:
        AnyRequest:
          Type: Api
          Properties:
            Path: /graphql
            Method: ANY
  GoalTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Goals
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema: 
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput: 
        ReadCapacityUnits: 25
        WriteCapacityUnits: 25